version: "3"

services:
  jekyll:
    build: .
    container_name: arifn.github.io
    command: bash -c "
      rm -f Gemfile.lock
      && bundle install
      && bundle exec jekyll serve --watch --port=4000 --host=0.0.0.0 --livereload --verbose"
    ports:
      - 4000:4000
    volumes:
      - .:/srv/jekyll
      - ./vendor/bundle:/usr/local/bundle
    environment:
      - JEKYLL_ENV=development